name: MacOS, Ubuntu, Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.12', '9.10', '9.8', '9.6']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id:   setup
      with:
        ghc-version:   ${{ matrix.ghc }}
        # cabal-version: latest
        cabal-update:  true

    - name: Restore cache
      uses: actions/cache/restore@v4
      id: cache
      env:
        key: ${{ runner.os }}-cabal-${{ steps.setup.outputs.cabal-version }}-ghc-${{ steps.setup.outputs.ghc-version }}
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key:          ${{ env.key }}-${{ github.sha }}
        restore-keys: ${{ env.key }}-

    - name: Install dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks -vnormal+nowrap all

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks -j1 -vnormal+nowrap all

    - name: Run tests
      run: cabal test -j1 -vnormal+nowrap all

    - name: Cache dependencies
      uses: actions/cache/save@v4
      if:   always()
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key:  ${{ steps.cache.outputs.cache-primary-key }}
